### ISSUE TITLE
Unable to find IWAD after building

### ISSUE THREAD

**Issue by DieMatratze** [alexey-lysiuk/doom64ex-macos-build#1]
Not sure if I'm using the build environment correctly: I ran `build.sh` in Terminal, and it produced a `doom64ex.app` in `doom64ex-osx-build-master/build/src/engine/Release`. I attempted to run it, placing the `.wad` and `.sf2` files in the same folder as the app, but it couldn't find the IWAD. I tried again, putting the two files within the app, next to the actual executable, but no luck. I tried a third time in Terminal, using the `-iwad` command described [here](http://z13.invisionfree.com/Doom64EX/index.php?showtopic=44&view=findpost&p=23176822), but again it insisted it could not find the IWAD. I remember reading something about a kex.wad; is that the file I'm missing? Like I said, I'm unsure if I've used the build environment correctly.

**Comment by alexey-lysiuk** [comment]
Yes, you are using it correctly. However the environment itself is not quite ready yet, mainly because of kex.wad isn't generated by BUILD_ALL target. How did you generated .wad and .sf2 by the way?

**Comment by DieMatratze** [comment]
I used WadGen to derive those files from the N64 ROM. It took some fudging, though; I used the fix described [here](http://z13.invisionfree.com/Doom64EX/index.php?showtopic=104&view=findpost&p=23184803).

**Comment by alexey-lysiuk** [comment]
In the current version .wad/.sf2 are generated by doom64ex executable using -wadgen /path/to/rom command line. This is another case that requires an improvement. At the moment the setup workflow isn't user friendly IMHO.

**Comment by alexey-lysiuk** [comment]
I have updated the build environment. After running `build.sh` Doom64EX application bundle will be created inside `deploy` directory.

To generate `.wad`/`.sf2`: execute `deploy/Doom64EX.app/Contents/MacOS/doom64ex -wadgen /full/path/to/rom` with the appropriate path to Doom 64 ROM file. `.wad` and `.sf2` will be created in the same directory. Copy them to `~/Library/Application Support/doom64ex` directory.

Now you can run Doom64EX by clicking on the application bundle.

**Comment by DieMatratze** [comment]
Thank you so much! I've played a bit through the first level, and so far everything's working great.

**Comment by alexey-lysiuk** [comment]
Nice to hear that.
End user setup procedures are still awful but most of problems were derived from Doom64EX itself.
