### ISSUE TITLE
Segmentation Fault 11 trying to enter Hectic

### ISSUE THREAD

**Issue by DieMatratze** [alexey-lysiuk/doom64ex-macos-build#2]
I used the secret exit in "Staging Area" to proceed to the level "Hectic." I was shown the text informing me I'd found Hectic (though the screen did not melt beforehand), but when I clicked to proceed, the game crashed. Using Terminal, I discovered the application underwent "Segmentation fault 11" when trying to transition. I attempted to use lldb to further diagnose the problem, but that wound up forcing me to restart my computer. Curiously, using the normal exit from "Staging Area" to "The Terraformer" worked just fine. Maybe it has something to do with Hectic's unusual level transition (there's no after-level stats screen; it goes straight to the intro text)? I'm including my crash log: [doom64ex_2016-05-29-164020.txt](https://github.com/alexey-lysiuk/doom64ex-osx-build/files/288571/doom64ex_2016-05-29-164020.txt)

"Only the best will reap its rewards" indeed. ;)

**Comment by alexey-lysiuk** [comment]
I doubt that the crash is OS X specific. The first problem is in `I_PNGReadData()` function that cannot handle images with a palette. But even if I will fix that it will crash later in the different place.

I think this must be reported to Doom64EX.

**Comment by alexey-lysiuk** [comment]
https://github.com/svkaiser/Doom64EX/issues/21
