### ISSUE TITLE
"SIGABRT" upon picking up Unmaker

### ISSUE THREAD

**Issue by DieMatratze** [alexey-lysiuk/doom64ex-macos-build#3]
Obtaining the Unmaker causes the current build to crash. It also causes the same problem of forcing me to restart my computer when I try to diagnose with `lldb`. When I restored my Terminal session, this is what I found:

```
Process 1804 stopped
* thread #1: tid = 0x1ae8b, 0x00007fff903b0f06 libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff903b0f06 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff903b0f06 <+10>: jae    0x7fff903b0f10            ; <+20>
    0x7fff903b0f08 <+12>: movq   %rax, %rdi
    0x7fff903b0f0b <+15>: jmp    0x7fff903ab7cd            ; cerror_nocancel
    0x7fff903b0f10 <+20>: retq
```

I'm also including two crash logs, the first from MAP29: Outpost Omega and the second from MAP12: Altar of Pain.

[doom64ex_2016-06-25-170935.txt](https://github.com/alexey-lysiuk/doom64ex-osx-build/files/333328/doom64ex_2016-06-25-170935.txt)
[doom64ex_2016-06-25-173035.txt](https://github.com/alexey-lysiuk/doom64ex-osx-build/files/333329/doom64ex_2016-06-25-173035.txt)

The way the crash acts in conjunction with `lldb` is similar to a previous glitch with MAP32: Hectic's sky. Should I report this error to the main Doom64EX project?

**Comment by alexey-lysiuk** [comment]
> Should I report this error to the main Doom64EX project?

In general yes, this is not the problem of this build environment. Not in this case perhaps as I already made a pull request with a fix.
